### ISSUE TITLE
Rewrite in C#

### ISSUE THREAD

**Issue by mSiotniHS** [Leoname3000/nelder-mead-method#1]
I insist that you rewrite the project in C# cuz Java is cringe and doesnt pass the vibe check.

**Comment by mSiotniHS** [comment]
I mean, why even consider using Java when there is godlike C# 🛐

**Comment by Leoname3000** [comment]
Yeah, that's right. Considering Java doesn't support operator overriding I need for the Point class I've planned, rewriting in C# might actually be the way to go 👍

**Comment by Leoname3000** [comment]
I decided to make a gigachad move and rewrite the project in Rust 💪🗿

**Comment by mSiotniHS** [comment]
That's the way to go! Will be thrilled to look at what you will end up making 👁👄👁
